version: "3.9"
services:
  everlasting-app:
    container_name: everlasting-app
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - "8070:3000"
    env_file:
      - .env
    restart: always
    networks:
      - everlasting-nt

networks:
  everlasting-nt:
    external: true
    driver: bridge
